<a href="https://colab.research.google.com/github/italo1055380/DeepLearn-Python/blob/main/Desafio_01_Representa%C3%A7%C3%A3o_do_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import collections
import numpy as np


# Carrega e ler os arquivos de texto: 
# Base Text - Matrix Representation I.txt
# Base Text - Matrix Representation II.txt

with open('/content/drive/MyDrive/Base Text - Matrix Representation I.txt', 'r') as file1, open('/content/drive/MyDrive/Base Text - Matrix Representation II.txt', 'r') as file2:
    file_content1 = file1.read()
    file_content2 = file2.read()

# Concatena os textos e imprime o conteudo em tela

    combined_content = file_content1 + file_content2
    print(combined_content)



De motu Circulari Fluidorum.


Hypothesis.
Resistentiam, quæ oritur ex defectu lubricitatis partium Fluidi, cæteris paribus, proportionalem esse velocitati, qua partes Fluidi separantur ab invicem.


Prop. LI. Theor. XXXVIII.
Si Cylindrus solidus infinitè longus in fluido uniformi & infinito circa axem positione datum uniformi cum motu revolvatur, & ab hujus impulsu solo agatur Fluidum in Orbem, perseveret autem fluidi pars unaquæque uniformiter in motu suo; dico quod tempora periodica partium fluidi sunt ut ipsarum distantiæ ab axe cylindri.


Sit AFL cylindrus uniformiter circa axem S in orbem actus, & circulis concentricis BGM, CHN, DIO, EKP, &c. distinguatur fluidum in orbes cylindricos innumeros concentricos solidos ejusdem crassitudinis. Et quoniam homogeneum est Fluidum, impressiones contiguorum orbium in se mutuò factæ, erunt (per Hypothesin) ut eorum translationes ab invicem & superficies contiguæ in quibus impressiones fiunt. Si impressio in Orbem aliquem major est vel minor

In [30]:

# Ler o conteúdo dos arquivos de texto e concatená-los em uma única string
with open('/content/drive/MyDrive/Base Text - Matrix Representation I.txt', 'r') as file1, open('/content/drive/MyDrive/Base Text - Matrix Representation II.txt', 'r') as file2:
    file_content1 = file1.read()
    file_content2 = file2.read()
    combined_content = file_content1 + file_content2

# Separar as palavras distintas da string e contar sua ocorrência
words = combined_content.split()
word_count = collections.Counter(words)

# Criar a matriz a partir das palavras distintas e seu total de ocorrências
word_list = sorted(set(words))
matrix = np.zeros((len(word_list), len(words)))
for i, word in enumerate(word_list):
    for j, text_word in enumerate(words):
        if word == text_word:
            matrix[i][j] = word_count[word]

# Imprimir a matriz

print(matrix)



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [34]:
with open('/content/drive/MyDrive/Base Text - Matrix Representation I.txt', 'r') as file1, open('/content/drive/MyDrive/Base Text - Matrix Representation II.txt', 'r') as file2:
    file_content1 = file1.read()
    file_content2 = file2.read()

# Concatena os textos e imprime o conteudo em tela

    combined_content = file_content1 + file_content2
    print(combined_content)


nome_arquivo = 'combined_content'

try:
    with open(nome_arquivo, 'rb') as arquivo:
        texto = arquivo.readlines()
        matriz = [linha.split() for linha in texto]
except FileNotFoundError:
    print(f"Arquivo '{nome_arquivo}' não encontrado.")
else:
    print(f"Lista de strings: {texto}")
    print(f"Matriz de strings: {matriz}")
    print("Linhas da matriz:")
    with open(nome_arquivo, 'rb') as arquivo:
        for linha in arquivo:
            print(linha.split())


De motu Circulari Fluidorum.


Hypothesis.
Resistentiam, quæ oritur ex defectu lubricitatis partium Fluidi, cæteris paribus, proportionalem esse velocitati, qua partes Fluidi separantur ab invicem.


Prop. LI. Theor. XXXVIII.
Si Cylindrus solidus infinitè longus in fluido uniformi & infinito circa axem positione datum uniformi cum motu revolvatur, & ab hujus impulsu solo agatur Fluidum in Orbem, perseveret autem fluidi pars unaquæque uniformiter in motu suo; dico quod tempora periodica partium fluidi sunt ut ipsarum distantiæ ab axe cylindri.


Sit AFL cylindrus uniformiter circa axem S in orbem actus, & circulis concentricis BGM, CHN, DIO, EKP, &c. distinguatur fluidum in orbes cylindricos innumeros concentricos solidos ejusdem crassitudinis. Et quoniam homogeneum est Fluidum, impressiones contiguorum orbium in se mutuò factæ, erunt (per Hypothesin) ut eorum translationes ab invicem & superficies contiguæ in quibus impressiones fiunt. Si impressio in Orbem aliquem major est vel minor

In [35]:
# Separar as palavras distintas da string e contar sua ocorrência
words = combined_content.split()
word_count = collections.Counter(words)

# Criar a matriz a partir das palavras distintas e seu total de ocorrências
word_list = sorted(set(words))
matrix = np.zeros((len(word_list), len(words)))
for i, word in enumerate(word_list):
    for j, text_word in enumerate(words):
        if word == text_word:
            matrix[i][j] = word_count[word]

# Imprimir a matriz

print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
